port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
# geodata-mode: true
# tcp-concurrent: true
allow-lan: true
bind-address: '*'
ipv6: true
external-controller: 0.0.0.0:8443
mode: rule
log-level: warning
profile:
  store-selected: true
  store-fake-ip: true
# sniffer:
#   enable: true
#   sniffing:
#     - tls
#     - http
#   skip-domain:
#     - '+.apple.com'
#     - '+.baidu.com'
#     - '+.jd.com'
#     - '+.mi.com'
#     - 'Mijia Cloud'
#   force-domain:
#     - '+'
#     - '+.amazonaws.com'
#     - '+.media.dssott.com'
#     - '+.facebook.com'
#     - '+.ggpht.com'
#     - '+.github.com'
#     - '+.google.com'
#     - '+.googleapi.com'
#     - '+.googlevideo.com'
#     - '+.gstatic.com'
#     - '+.netflix.com'
#     - '+.nflxvideo.net'
#     - '+.youtube.com'
#     - '+.ytimg.com'
#   port-whitelist:
#     - 1-65535
#     #- 443
#     #- 80
#     #- 8080
#     #- 8000-9000
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  default-nameserver:
    #- "tcp://[::1]:6054"
    #- "[::1]:6054"
    #- "tcp://127.0.0.1:6054"
    #- "127.0.0.1:6054"
    #- "tcp://192.168.11.1:6054"
    #- "192.168.11.1:6054"
    #- "tcp://192.168.11.1:53"
    #- "192.168.11.1:53"
    #- "tcp://101.42.236.152:777"
    #- "tcp://b.iqiq.io:777"
    #- "tcp://183.255.114.14:777"
    #- "tcp://h.iqiq.io:777"
    #- "tcp://36.134.147.213:777"
    #- "tcp://j.iqiq.io:777"
    #- "tcp://162.14.132.76:53"
    - "tcp://[2402:4e00::]"
    - "tcp://119.29.29.29"
    - "tcp://[2400:3200:baba::1]"
    - "tcp://[2400:3200::1]"
    - "tcp://223.6.6.6"
    - "tcp://223.5.5.5"
    - "tcp://[2400:da00::6666]"
    - "tcp://180.76.76.76"
    - "tcp://[240C::6666]"
    - "tcp://[240C::6644]"
    - "tcp://[2620:fe::fe:11]:53"
    - "tcp://[2620:fe::11]:53"
    - "tcp://149.112.112.11:53"
    - "tcp://9.9.9.11:53"
    - "tcp://[2620:fe::9]:53"
    - "tcp://[2620:fe::fe]:53"
    - "tcp://149.112.112.112:53"
    - "tcp://9.9.9.9:53"
    - "tcp://[2620:fe::fe:10]:53"
    - "tcp://[2620:fe::10]:53"
    - "tcp://149.112.112.10:53"
    - "tcp://9.9.9.10:53"
    - "tcp://[2606:4700:4700::1002]:53"
    - "tcp://[2606:4700:4700::1112]:53"
    - "tcp://1.0.0.2:53"
    - "tcp://1.1.1.2:53"
    - "tcp://[2606:4700:4700::1001]:53"
    - "tcp://[2606:4700:4700::1111]:53"
    - "tcp://1.0.0.1:53"
    - "tcp://1.1.1.1:53"
    #- "tcp://[2a10:50c0::ad2:ff]:53"
    #- "tcp://[2a10:50c0::ad1:ff]:53"
    #- "tcp://94.140.15.15:53"
    #- "tcp://94.140.14.14:53"
    #- "tcp://[2a10:50c0::2:ff]:53"
    #- "tcp://[2a10:50c0::1:ff]:53"
    #- "tcp://94.140.14.141:53"
    #- "tcp://94.140.14.140:53"
    #- "tcp://[2001:620:0:ff::3]:53"
    #- "tcp://[2001:620:0:ff::2]:53"
    #- "tcp://130.59.31.251:53"
    #- "tcp://130.59.31.248:53"
    #- "tcp://[2001:148f:fffe::1]:53"
    #- "tcp://[2001:148f:ffff::1]:53"
    #- "tcp://185.43.135.1:53"
    #- "tcp://193.17.47.1:53"
    #- "tcp://[2001:8b0::2021]:53"
    #- "tcp://[2001:8b0::2020]:53"
    #- "tcp://217.169.20.21:53"
    #- "tcp://217.169.20.20:53"
    #- "tcp://[2a01:3a0:53:53::]:5353"
    #- "tcp://[2a01:3a0:53:53::]:53"
    #- "tcp://89.233.43.71:5353"
    #- "tcp://89.233.43.71:53"
    #- "tcp://[2001:67c:28a4::]:5353"
    #- "tcp://[2001:67c:28a4::]:53"
    #- "tcp://91.239.100.100:5353"
    #- "tcp://91.239.100.100:53"
    #- "tcp://[2001:878:0:e000:82:e1:f4:a6]:5353"
    #- "tcp://[2001:878:0:e000:82:e1:f4:a6]:53"
    #- "tcp://130.225.244.166:5353"
    #- "tcp://130.225.244.166:53"
    #- "tcp://[2001:878:0:e000:82:e2:a1:22]:5353"
    #- "tcp://[2001:878:0:e000:82:e2:a1:22]:53"
    #- "tcp://130.226.161.34:5353"
    #- "tcp://130.226.161.34:53"
    #- "tcp://[2a00:fbe0:1:3802::3]:5353"
    #- "tcp://[2a00:fbe0:1:3802::3]:53"
    #- "tcp://185.38.27.139:5353"
    #- "tcp://185.38.27.139:53"
    #- "tcp://[2001:418:8006::12]:5353"
    #- "tcp://[2001:418:8006::12]:53"
    #- "tcp://198.180.150.12:5353"
    #- "tcp://198.180.150.12:53"
    - "tcp://[2001:4860:4860::8888]:53"
    - "tcp://[2001:4860:4860::8844]:53"
    - "tcp://8.8.8.8:53"
    - "tcp://8.8.4.4:53"
    #- tcp://101.226.4.6
    #- 101.226.4.6
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
    - "ipv6check-http.steamcontent.com"
    - "ipv6check-udp.steamcontent.com"
#   proxy-server-nameserver:
#     - "tcp://[::1]:6054"
#     - "[::1]:6054"
#     - "tcp://127.0.0.1:6054"
#     - "127.0.0.1:6054"
#     - "tcp://192.168.11.1:6054"
#     - "192.168.11.1:6054"
#     - "tcp://192.168.11.1:53"
#     - "192.168.11.1:53"
  nameserver:
    #- "https://rubyfish.cn/dns-query"
    #- "tls://rubyfish.cn"
    #- "https://v6.rubyfish.cn/dns-query"
    #- "tls://v6.rubyfish.cn"
    #- "https://dns.rubyfish.cn/dns-query"
    #- "tls://dns.rubyfish.cn"
    #- "https://1.12.12.12/dns-query"
    #- "https://120.53.53.53/dns-query"
    #- "https://doh.pub/dns-query"
    #- "tls://1.12.12.12"
    #- "tls://120.53.53.53"
    #- "tls://dot.pub"
    #- "https://223.6.6.6/dns-query"
    #- "https://223.5.5.5/dns-query"
    #- "https://dns.alidns.com/dns-query"
    #- "tls://223.6.6.6"
    #- "tls://223.5.5.5"
    #- "tls://dns.alidns.com"
    #- "https://doh.360.cn/dns-query"
    #- "tls://dot.360.cn"
    #- "https://dns.ipv6dns.com/dns-query"
    #- "tls://dns.ipv6dns.com"
    #- "tcp://[::1]:6054"
    #- "[::1]:6054"
    #- "tcp://127.0.0.1:6054"
    #- "127.0.0.1:6054"
    #- "tcp://192.168.11.1:6054"
    #- "192.168.11.1:6054"
    #- "tcp://192.168.11.1:53"
    #- "192.168.11.1:53"
    - https://a.vvvglass.com/sz
    - tls://c.vvvglass.com
    - tls://h.iqiq.io
    - tls://j.iqiq.io
    - tls://x.vvvglass.com
    - tls://b.iqiq.io
    - https://a.vvvglass.com/iq
    - https://a.vvvglass.com/cdn
    - tls://a.vvvglass.com:5432
    - https://i.vvvglass.com/iq
    - tls://i.vvvglass.com:5432
    - https://worldwide.vvvglass.com/iq
    - https://a.vvvglass.com/am
    - https://a.vvvglass.com/hk
    - https://a.vvvglass.com/us
    - https://cdn.iqiq.io/dns-query
    - https://proxy.iqiq.io/dns-query
    - https://a.passcloud.xyz/dns-query
    - https://a.passcloud.xyz/sz
    - https://a.passcloud.xyz/cdn
    - https://a.passcloud.xyz/am
    - https://a.passcloud.xyz/hk
    - https://a.passcloud.xyz/us
    - tls://a.passcloud.xyz:5432
    - https://b.vvvglass.com/iq
    - tls://b.vvvglass.com:5432
    - tls://c.passcloud.xyz
    - https://i.passcloud.xyz/dns-query
    - tls://i.passcloud.xyz:5432
    - https://worldwide.passcloud.xyz/dns-query
    - tls://x.passcloud.xyz
    #- "https://dh-dns.global-idt.net/dns-query"
    #- "tls://dh-dns.global-idt.net:853"
    #- "https://162.14.132.109/dns-query"
    #- "tls://162.14.132.109:853"
    #- "https://dh-dns.global-idc.net/dns-query"
    #- "tls://dh-dns.global-idc.net:853"
    #- "https://162.14.132.76/dns-query"
    #- "tls://162.14.132.76:853"
    #- https://i.233py.com/dns-query
    #- https://dns.233py.com/dns-query
    #- tls://v.233py.com
    #- tls://i.233py.com
    #- "https://dns.adguard.com/dns-query"
    #- "tls://dns.adguard.com:853"
    #- "https://dns-unfiltered.adguard.com/dns-query"
    #- "tls://dns-unfiltered.adguard.com:853"
    #- "https://dns.switch.ch/dns-query"
    #- "tls://dns.switch.ch:853"
    #- "https://odvr.nic.cz/dns-query"
    #- "tls://odvr.nic.cz:853"
    #- "https://dns.aa.net.uk/dns-query"
    #- "tls://dns.aa.net.uk:853"
    #- "https://unicast.uncensoreddns.org/dns-query"
    #- "https://unicast.censurfridns.dk/dns-query"
    #- "tls://unicast.uncensoreddns.org:853"
    #- "tls://unicast.censurfridns.dk:853"
    #- "https://anycast.uncensoreddns.org/dns-query"
    #- "https://anycast.censurfridns.dk/dns-query"
    #- "tls://anycast.uncensoreddns.org:853"
    #- "tls://anycast.censurfridns.dk:853"
    #- "https://deic-lgb.anycast.censurfridns.dk/dns-query"
    #- "tls://deic-lgb.anycast.censurfridns.dk:853"
    #- "https://deic-ore.anycast.censurfridns.dk/dns-query"
    #- "tls://deic-ore.anycast.censurfridns.dk:853"
    #- "https://kracon.anycast.censurfridns.dk/dns-query"
    #- "tls://kracon.anycast.censurfridns.dk:853"
    #- "https://rgnet-iad.anycast.censurfridns.dk/dns-query"
    #- "tls://rgnet-iad.anycast.censurfridns.dk:853"
  #fallback:
    #- "https://dns.google/dns-query"
    #- "tls://dns.google"
    #- "https://security.cloudflare-dns.com/dns-query"
    #- "tls://security.cloudflare-dns.com"
    #- "https://mozilla.cloudflare-dns.com/dns-query"
    #- "https://cloudflare-dns.com/dns-query"
    #- "tls://1dot1dot1dot1.cloudflare-dns.com"
    #- "tls://one.one.one.one"
    #- "https://dns11.quad9.net/dns-query"
    #- "tls://dns11.quad9.net"
    #- "https://dns.quad9.net/dns-query"
    #- "tls://dns.quad9.net"
    #- "https://dns10.quad9.net/dns-query"
    #- "tls://dns10.quad9.net"
    #- tcp://[fd00::1]:6053
    #- "[fd00::1]:6053"
    #- tcp://[fd00::1]:6054
    #- "[fd00::1]:6054"
    #- tcp://[fd00::1]:7874
    #- "[fd00::1]:7874"
    #- tcp://[fd00::1]:53
    #- "[fd00::1]:53"
    #- tcp://[fd00::1]
    #- "[fd00::1]"
    #- tcp://[fd00::1]:7054
    #- "[fd00::1]:7054"
  #fallback-filter:
    #geoip: true
    #geoip-code: CN
    #ipcidr:
      #- 240.0.0.0/4
    #domain:
      #- '+.line.me'
      #- '+.google.com'
      #- '+.facebook.com'
      #- '+.youtube.com'
  #nameserver-policy:
  #  'www.baidu.com': '114.114.114.114'
  #  '+.internal.crop.com': '10.0.0.1'
#tun:
#  enable: true
#  stack: system
#  dns-hijack:
#    - "tcp://[2402:4e00::]:53"
#    - "[2400:3200:baba::1]:53"
#    - "tcp://119.29.29.29:53"
#    - "223.6.6.6:53"
#  auto-route: true
#  auto-detect-interface: true
