port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
allow-lan: true
bind-address: '*'
find-process-mode: strict
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
ipv6: true
mode: rule
log-level: warning
tcp-concurrent: true
global-client-fingerprint: ios
#hosts:
#  '*.clash.dev': 127.0.0.1
#  '.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
profile:
  store-selected: true
  store-fake-ip: false
#sniffer:
#  enable: true
#  force-dns-mapping: true
#  parse-pure-ip: true
#  override-destination: false
#  sniff:
#    TLS:
#      ports: [80, 443, 853, 8000, 8443]
#    HTTP:
#      ports: [80, 443, 853, 8000, 8080-8880]
#      override-destination: true
#  force-domain:
#    - '+'
#    - '+.amazonaws.com'
#    - '+.media.dssott.com'
#    - '+.facebook.com'
#    - '+.ggpht.com'
#    - '+.github.com'
#    - '+.google.com'
#    - '+.googleapi.com'
#    - '+.googlevideo.com'
#    - '+.gstatic.com'
#    - '+.netflix.com'
#    - '+.nflxvideo.net'
#    - "+.v2ex.com"
#    - '+.youtube.com'
#    - '+.ytimg.com'
#  skip-domain:
#    - '+.apple.com'
#    - '+.baidu.com'
#    - '+.jd.com'
#    - '+.mi.com'
#    - 'Mijia Cloud'
dns:
  enable: true
  prefer-h3: true
  listen: "[::]:7874"
  ipv6: true
  default-nameserver:
    - "tls://[2001:4860:4860::8844]:853"
    - "tls://[2001:4860:4860::8888]:853"
    - "tls://8.8.4.4:853"
    - "tls://8.8.8.8:853"
    - "tls://[2606:4700:4700::1002]:853"
    - "tls://[2606:4700:4700::1112]:853"
    - "tls://1.0.0.2:853"
    - "tls://1.1.1.2:853"
    - "tls://[2606:4700:4700::1001]:853"
    - "tls://[2606:4700:4700::1111]:853"
    - "tls://1.0.0.1:853"
    - "tls://1.1.1.1:853"
    #- "tls://[2620:fe::fe:11]:853"
    #- "tls://[2620:fe::11]:853"
    #- "tls://149.112.112.11:853"
    #- "tls://9.9.9.11:853"
    #- "tls://[2620:fe::9]:853"
    #- "tls://[2620:fe::fe]:853"
    #- "tls://149.112.112.112:853"
    #- "tls://9.9.9.9:853"
    #- "tls://[2620:fe::fe:10]:853"
    #- "tls://[2620:fe::10]:853"
    #- "tls://149.112.112.10:853"
    #- "tls://9.9.9.10:853"
    #- "tcp://[::1]:853"
    #- "[::1]:6054"
    #- "tcp://127.0.0.1:6054"
    #- "127.0.0.1:6054"
    #- "tcp://192.168.11.1:6054"
    #- "192.168.11.1:6054"
    #- "tcp://192.168.11.1:53"
    #- "192.168.11.1:53"
    #- "tcp://101.42.236.152:777"
    #- "tcp://b.iqiq.io:777"
    #- "tcp://183.255.114.14:777"
    #- "tcp://h.iqiq.io:777"
    #- "tcp://36.134.147.213:777"
    #- "tcp://j.iqiq.io:777"
    #- "tcp://162.14.132.76:53"
    #- "[2402:4e00::]:53"
    #- "119.29.29.29:53"
    #- "[2400:3200:baba::1]:53"
    #- "[2400:3200::1]:53"
    #- "223.6.6.6:53"
    #- "223.5.5.5:53"
    #- "[2400:da00::6666]:53"
    #- "180.76.76.76:53"
    #- "[240C::6666]:53"
    #- "[240C::6644]:53"
    #- "tcp://[2a10:50c0::ad2:ff]:53"
    #- "tcp://[2a10:50c0::ad1:ff]:53"
    #- "tcp://94.140.15.15:53"
    #- "tcp://94.140.14.14:53"
    #- "tcp://[2a10:50c0::2:ff]:53"
    #- "tcp://[2a10:50c0::1:ff]:53"
    #- "tcp://94.140.14.141:53"
    #- "tcp://94.140.14.140:53"
    #- "tcp://[2001:620:0:ff::3]:53"
    #- "tcp://[2001:620:0:ff::2]:53"
    #- "tcp://130.59.31.251:53"
    #- "tcp://130.59.31.248:53"
    #- "tcp://[2001:148f:fffe::1]:53"
    #- "tcp://[2001:148f:ffff::1]:53"
    #- "tcp://185.43.135.1:53"
    #- "tcp://193.17.47.1:53"
    #- "tcp://[2001:8b0::2021]:53"
    #- "tcp://[2001:8b0::2020]:53"
    #- "tcp://217.169.20.21:53"
    #- "tcp://217.169.20.20:53"
    #- "tcp://[2a01:3a0:53:53::]:5353"
    #- "tcp://[2a01:3a0:53:53::]:53"
    #- "tcp://89.233.43.71:5353"
    #- "tcp://89.233.43.71:53"
    #- "tcp://[2001:67c:28a4::]:5353"
    #- "tcp://[2001:67c:28a4::]:53"
    #- "tcp://91.239.100.100:5353"
    #- "tcp://91.239.100.100:53"
    #- "tcp://[2001:878:0:e000:82:e1:f4:a6]:5353"
    #- "tcp://[2001:878:0:e000:82:e1:f4:a6]:53"
    #- "tcp://130.225.244.166:5353"
    #- "tcp://130.225.244.166:53"
    #- "tcp://[2001:878:0:e000:82:e2:a1:22]:5353"
    #- "tcp://[2001:878:0:e000:82:e2:a1:22]:53"
    #- "tcp://130.226.161.34:5353"
    #- "tcp://130.226.161.34:53"
    #- "tcp://[2a00:fbe0:1:3802::3]:5353"
    #- "tcp://[2a00:fbe0:1:3802::3]:53"
    #- "tcp://185.38.27.139:5353"
    #- "tcp://185.38.27.139:53"
    #- "tcp://[2001:418:8006::12]:5353"
    #- "tcp://[2001:418:8006::12]:53"
    #- "tcp://198.180.150.12:5353"
    #- "tcp://198.180.150.12:53"
    #- tcp://101.226.4.6
    #- 101.226.4.6
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    # LAN
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    # NTP服务
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - "time-ios.apple.com"
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    # 网易云音乐
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    # 百度音乐
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    # 酷狗音乐
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    # 酷我音乐
    - '*.kuwo.cn'
    # JOOX音乐
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    # QQ音乐
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    # 虾米音乐
    - '*.xiami.com'
    # 咪咕音乐
    - '*.music.migu.cn'
    - 'music.migu.cn'
    # Windows网络连通性检测
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    # QQ登录
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - "+.qq.com"
    - "+.tencent.com"
    # 任天堂Switch
    - '+.srv.nintendo.net'
    - "*.n.n.srv.nintendo.net"
    # Sony PlayStation
    - '+.stun.playstation.net'
    # Microsoft Xbox
    - "xbox.*.*.microsoft.com"
    - 'xbox.*.microsoft.com'
    - "*.*.xboxlive.com"
    - 'xnotify.xboxlive.com'
    # Wotgame
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    # Golang
    - 'proxy.golang.org'
    # STUN
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - "+.stun.*.*.*.*.*"
    # Linksys Router
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # ASUS Router
    - '*.router.asus.com'
    # Apple Software Update Service
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    # Google
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    # Netflix
    - '+.nflxvideo.net'
    # FinalFantasy XIV Worldwide Server & CN Server
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - "*.ff14.sdo.com"
    # Bilibili
    - '*.mcdn.bilivideo.cn'
    # Disney Plus
    - "+.media.dssott.com"
    # shark007 Codecs 
    - "shark007.net"
    # Mijia
    - "Mijia Cloud"
    # 招商银行
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    # AdGuard
    - "local.adguard.org"
    # 迅雷
    - "+.sandai.net"
    - "+.n0808.com"
    - "ipv6check-http.steamcontent.com"
    - "ipv6check-udp.steamcontent.com"
  proxy-server-nameserver:
    - "tls://[2001:4860:4860::8844]:853"
    - "tls://[2001:4860:4860::8888]:853"
    - "tls://8.8.4.4:853"
    - "tls://8.8.8.8:853"
    - "tls://dns.google:853"
    - "https://[2001:4860:4860::8844]:443/dns-query"
    - "https://[2001:4860:4860::8888]:443/dns-query"
    - "https://8.8.4.4:443/dns-query"
    - "https://8.8.8.8:443/dns-query"
    - "https://dns.google:443/dns-query"
    - "tls://[2606:4700:4700::1002]:853"
    - "tls://[2606:4700:4700::1112]:853"
    - "tls://1.0.0.2:853"
    - "tls://1.1.1.2:853"
    - "tls://security.cloudflare-dns.com:853"
    - "https://security.cloudflare-dns.com:443/dns-query"
    - "tls://[2606:4700:4700::1001]:853"
    - "tls://[2606:4700:4700::1111]:853"
    - "tls://1.0.0.1:853"
    - "tls://1.1.1.1:853"
    - "tls://1dot1dot1dot1.cloudflare-dns.com:853"
    - "tls://cloudflare-dns.com:853"
    - "tls://one.one.one.one:853"
    - "https://[2606:4700:4700::1001]:443/dns-query"
    - "https://[2606:4700:4700::1111]:443/dns-query"
    - "https://1.0.0.1:443/dns-query"
    - "https://1.1.1.1:443/dns-query"
    - "https://cloudflare-dns.com:443/dns-query"
    - "https://mozilla.cloudflare-dns.com:443/dns-query"
  nameserver:
    - "tls://[2400:3200:baba::1]:853"
    - "tls://[2400:3200::1]:853"
    - "tls://223.6.6.6:853"
    - "tls://223.5.5.5:853"
    - "tls://dns.alidns.com:853"
    - "https://[2400:3200:baba::1]:443/dns-query"
    - "https://[2400:3200::1]:443/dns-query"
    - "https://223.6.6.6:443/dns-query"
    - "https://223.5.5.5:443/dns-query"
    - "https://dns.alidns.com:443/dns-query"
    - "tls://1.12.12.12:853"
    - "tls://120.53.53.53:853"
    - "tls://dot.pub:853"
    - "https://1.12.12.12:443/dns-query"
    - "https://120.53.53.53:443/dns-query"
    - "https://doh.pub:443/dns-query"
    #- "tls://[2620:fe::fe:11]:853"
    #- "tls://[2620:fe::11]:853"
    #- "tls://149.112.112.11:853"
    #- "tls://9.9.9.11:853"
    #- "tls://dns11.quad9.net:853"
    #- "https://dns11.quad9.net:443/dns-query"
    #- "tls://[2620:fe::9]:853"
    #- "tls://[2620:fe::fe]:853"
    #- "tls://149.112.112.112:853"
    #- "tls://9.9.9.9:853"
    #- "tls://dns.quad9.net:853"
    #- "https://dns.quad9.net:443/dns-query"
    #- "tls://[2620:fe::fe:10]:853"
    #- "tls://[2620:fe::10]:853"
    #- "tls://149.112.112.10:853"
    #- "tls://9.9.9.10:853"
    #- "tls://dns10.quad9.net:853"
    #- "https://dns10.quad9.net:443/dns-query"
    #- "tls://dot.360.cn:853"
    #- "https://doh.360.cn:443/dns-query"
    #- "https://v6.rubyfish.cn:443/dns-query"
    #- "tls://v6.rubyfish.cn:853"
    #- "https://rubyfish.cn:443/dns-query"
    #- "tls://rubyfish.cn:853"
    #- "https://dns.rubyfish.cn:443/dns-query"
    #- "tls://dns.rubyfish.cn:853"
    #- "https://dns.ipv6dns.com:443/dns-query"
    #- "tls://dns.ipv6dns.com:853"
    #- "tcp://[::1]:853"
    #- "[::1]:6054"
    #- "tcp://127.0.0.1:6054"
    #- "127.0.0.1:6054"
    #- "tcp://192.168.11.1:6054"
    #- "192.168.11.1:6054"
    #- "tcp://192.168.11.1:53"
    #- "192.168.11.1:53"
    #- "https://dh-dns.global-idt.net/dns-query"
    #- "tls://dh-dns.global-idt.net:853"
    #- "https://162.14.132.109/dns-query"
    #- "tls://162.14.132.109:853"
    #- "https://dh-dns.global-idc.net/dns-query"
    #- "tls://dh-dns.global-idc.net:853"
    #- "https://162.14.132.76/dns-query"
    #- "tls://162.14.132.76:853"
    #- https://i.233py.com/dns-query
    #- https://dns.233py.com/dns-query
    #- tls://v.233py.com
    #- tls://i.233py.com
    #- "https://dns.adguard.com/dns-query"
    #- "tls://dns.adguard.com:853"
    #- "https://dns-unfiltered.adguard.com/dns-query"
    #- "tls://dns-unfiltered.adguard.com:853"
    #- "https://dns.switch.ch/dns-query"
    #- "tls://dns.switch.ch:853"
    #- "https://odvr.nic.cz/dns-query"
    #- "tls://odvr.nic.cz:853"
    #- "https://dns.aa.net.uk/dns-query"
    #- "tls://dns.aa.net.uk:853"
    #- "https://unicast.uncensoreddns.org/dns-query"
    #- "https://unicast.censurfridns.dk/dns-query"
    #- "tls://unicast.uncensoreddns.org:853"
    #- "tls://unicast.censurfridns.dk:853"
    #- "https://anycast.uncensoreddns.org/dns-query"
    #- "https://anycast.censurfridns.dk/dns-query"
    #- "tls://anycast.uncensoreddns.org:853"
    #- "tls://anycast.censurfridns.dk:853"
    #- "https://deic-lgb.anycast.censurfridns.dk/dns-query"
    #- "tls://deic-lgb.anycast.censurfridns.dk:853"
    #- "https://deic-ore.anycast.censurfridns.dk/dns-query"
    #- "tls://deic-ore.anycast.censurfridns.dk:853"
    #- "https://kracon.anycast.censurfridns.dk/dns-query"
    #- "tls://kracon.anycast.censurfridns.dk:853"
    #- "https://rgnet-iad.anycast.censurfridns.dk/dns-query"
    #- "tls://rgnet-iad.anycast.censurfridns.dk:853"
  fallback:
    - "tls://[2001:4860:4860::8844]:853"
    - "tls://[2001:4860:4860::8888]:853"
    - "tls://8.8.4.4:853"
    - "tls://8.8.8.8:853"
    - "tls://dns.google:853"
    - "https://[2001:4860:4860::8844]:443/dns-query"
    - "https://[2001:4860:4860::8888]:443/dns-query"
    - "https://8.8.4.4:443/dns-query"
    - "https://8.8.8.8:443/dns-query"
    - "https://dns.google:443/dns-query"
    - "tls://[2606:4700:4700::1002]:853"
    - "tls://[2606:4700:4700::1112]:853"
    - "tls://1.0.0.2:853"
    - "tls://1.1.1.2:853"
    - "tls://security.cloudflare-dns.com:853"
    - "https://[2606:4700:4700::1002]:443/dns-query"
    - "https://[2606:4700:4700::1112]:443/dns-query"
    - "https://1.0.0.2:443/dns-query"
    - "https://1.1.1.2:443/dns-query"
    - "https://security.cloudflare-dns.com:443/dns-query"
    - "tls://[2606:4700:4700::1001]:853"
    - "tls://[2606:4700:4700::1111]:853"
    - "tls://1.0.0.1:853"
    - "tls://1.1.1.1:853"
    - "tls://1dot1dot1dot1.cloudflare-dns.com:853"
    - "tls://cloudflare-dns.com:853"
    - "tls://one.one.one.one:853"
    - "https://[2606:4700:4700::1001]:443/dns-query"
    - "https://[2606:4700:4700::1111]:443/dns-query"
    - "https://1.0.0.1:443/dns-query"
    - "https://1.1.1.1:443/dns-query"
    - "https://cloudflare-dns.com:443/dns-query"
    - "https://mozilla.cloudflare-dns.com:443/dns-query"
    #- "tls://dns11.quad9.net:853"
    #- "https://dns11.quad9.net:443/dns-query"
    #- "tls://dns.quad9.net:853"
    #- "https://dns.quad9.net:443/dns-query"
    #- "tls://dns10.quad9.net:853"
    #- "https://dns10.quad9.net:443/dns-query"
    #- https://a.vvvglass.com/sz
    #- "tls://c.vvvglass.com:853"
    #- "tls://h.iqiq.io:853"
    #- "tls://j.iqiq.io:853"
    #- "tls://x.vvvglass.com:853"
    #- "tls://b.iqiq.io:853"
    #- https://a.vvvglass.com/iq
    #- https://a.vvvglass.com/cdn
    #- "tls://a.vvvglass.com:5432"
    #- https://i.vvvglass.com/iq
    #- "tls://i.vvvglass.com:5432"
    #- https://worldwide.vvvglass.com/iq
    #- https://a.vvvglass.com/am
    #- https://a.vvvglass.com/hk
    #- https://a.vvvglass.com/us
    #- https://cdn.iqiq.io/dns-query
    #- https://proxy.iqiq.io/dns-query
    #- https://a.passcloud.xyz/dns-query
    #- https://a.passcloud.xyz/sz
    #- https://a.passcloud.xyz/cdn
    #- https://a.passcloud.xyz/am
    #- https://a.passcloud.xyz/hk
    #- https://a.passcloud.xyz/us
    #- "tls://a.passcloud.xyz:5432"
    #- https://b.vvvglass.com/iq
    #- "tls://b.vvvglass.com:5432"
    #- "tls://c.passcloud.xyz"
    #- https://i.passcloud.xyz/dns-query
    #- "tls://i.passcloud.xyz:5432"
    #- https://worldwide.passcloud.xyz/dns-query
    #- tls://x.passcloud.xyz"
    #- "tcp://[::1]:853"
    #- "[fd00::1]:6053"
    #- tcp://[fd00::1]:6054
    #- "[fd00::1]:6054"
    #- tcp://[fd00::1]:7874
    #- "[fd00::1]:7874"
    #- tcp://[fd00::1]:53
    #- "[fd00::1]:53"
    #- tcp://[fd00::1]
    #- "[fd00::1]"
    #- tcp://[fd00::1]:7054
    #- "[fd00::1]:7054"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - "gfw"
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - 4.bing.com
      - bat.bing.com
      - business.bing.com
      - c.bing.com
      - cn.bing.com
      - edgeservices.bing.com
      - global.bing.com
      - r.bing.com
      - sydney.bing.com
      - testfamilysafety.bing.com
      - th.bing.com
      - www.bing.com
      - www2.bing.com
      - "+.bing.com"
      - "+.bingapis.com"
      - s.cn.bing.net
      - s2.cn.bing.net
      - s3.cn.bing.net
      - s4.cn.bing.net
      - ts1.cn.mm.bing.net
      - ts2.cn.mm.bing.net
      - ts3.cn.mm.bing.net
      - ts4.cn.mm.bing.net
      - tse1.mm.bing.net
      - tse2.mm.bing.net
      - "+.bing.net"
      - "+.line.me"
      - "+.githubusercontent.com"
      - "+.google.com"
      - "+.googlevideo.com"
      - '+.facebook.com'
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - "+.wikipedia.org"
      - '+.youtube.com'
  #nameserver-policy:
  #  'www.baidu.com': '114.114.114.114'
  #  '+.internal.crop.com': '10.0.0.1'
#tun:
#  enable: true
#  stack: system
#  dns-hijack:
#    - "tcp://[2402:4e00::]:53"
#    - "[2400:3200:baba::1]:53"
#    - "tcp://119.29.29.29:53"
#    - "223.6.6.6:53"
#  auto-route: true
#  auto-detect-interface: true
