payload:
  - AND,((DOMAIN,edge-chat.facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,gateway.facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,m.facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,research.facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,www.facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,facebook.com),(NETWORK,tcp))
  - AND,((DOMAIN,portal.fb.com),(NETWORK,tcp))
  - AND,((DOMAIN,fb.com),(NETWORK,tcp))
  # DOMAIN-SUFFIX,fb.me
  # DOMAIN-SUFFIX,fbcdn.com
  - AND,((DOMAIN,scontent.fhkg1-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg2-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg3-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg4-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg5-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg6-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg7-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg8-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg9-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent.fhkg10-1.fna.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw1-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw2-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw3-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw4-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw5-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-dfw5-2.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-hkg1-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-hkg2-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-hkg3-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-hkg4-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-iad1-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-iad2-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-iad3-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-lax3-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-lax3-2.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,scontent-nrt1-1.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,static.xx.fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,fbcdn.net),(NETWORK,tcp))
  - AND,((DOMAIN,platform-lookaside.fbsbx.com),(NETWORK,tcp))
  - AND,((DOMAIN,fbsbx.com),(NETWORK,tcp))
  # DOMAIN-SUFFIX,cdninstagram.com
  # DOMAIN-SUFFIX,instagr.am
  - AND,((DOMAIN,instagram.com),(NETWORK,tcp))
